export const PLACE_CATEGORIES = [
  {
    id: 'attraction',
    label: 'Attractions',
    emoji: '🏛️',
    icon: 'Landmark',
    color: '#8B5CF6',
    osmTag: 'tourism=attraction',
  },
  {
    id: 'food',
    label: 'Food & Dining',
    emoji: '🍜',
    icon: 'Utensils',
    color: '#F59E0B',
    osmTag: 'amenity=restaurant',
  },
  {
    id: 'cafe',
    label: 'Cafes',
    emoji: '☕',
    icon: 'Coffee',
    color: '#D97706',
    osmTag: 'amenity=cafe',
  },
  {
    id: 'hotel',
    label: 'Stays & Hotels',
    emoji: '🏨',
    icon: 'Hotel',
    color: '#3B82F6',
    osmTag: 'tourism=hotel',
  },
  {
    id: 'budget',
    label: 'Budget Spots',
    emoji: '🏷️',
    icon: 'Tag',
    color: '#10B981',
    osmTag: 'tourism=hostel',
  },
  {
    id: 'park',
    label: 'Parks & Nature',
    emoji: '🌳',
    icon: 'Trees',
    color: '#22C55E',
    osmTag: 'leisure=park',
  },
  {
    id: 'hospital',
    label: 'Hospitals',
    emoji: '🏥',
    icon: 'Hospital',
    color: '#EC4899',
    osmTag: 'amenity=hospital',
  },
  {
    id: 'police',
    label: 'Police Stations',
    emoji: '👮',
    icon: 'ShieldAlert',
    color: '#6366F1',
    osmTag: 'amenity=police',
  },
];

export const REPORT_CATEGORIES = [
  { id: 'hazard', label: 'Road Hazard', emoji: '⚠️', severity: 3, color: '#F59E0B' },
  { id: 'accident', label: 'Accident Prone', emoji: '💥', severity: 4, color: '#EF4444' },
  { id: 'harassment', label: 'Safety / Harassment', emoji: '🚨', severity: 5, color: '#DC2626' },
  { id: 'lighting', label: 'Poor Street Lighting', emoji: '🌙', severity: 3, color: '#8B5CF6' },
  { id: 'garbage', label: 'Garbage Overflow', emoji: '🗑️', severity: 2, color: '#84CC16' },
  { id: 'flooding', label: 'Waterlogging / Flood', emoji: '🌊', severity: 4, color: '#06B6D4' },
  { id: 'traffic', label: 'Heavy Congestion', emoji: '🚦', severity: 2, color: '#EAB308' },
  { id: 'other', label: 'Other Issue', emoji: '📌', severity: 1, color: '#64748B' },
];
